export const generateESOPGrantPrompt = (formData: any): string => {
    const data = {
        company_name: formData.company_name,
        company_type: formData.company_type || 'Private Limited',
        cin: formData.cin,
        registered_office: formData.registered_office,
        plan_name: formData.plan_name,
        grant_letter_number: formData.grant_letter_number || '',
        grant_date: formData.grant_date,
        effective_date: formData.effective_date,
        employee_name: formData.employee_name,
        employee_id: formData.employee_id,
        designation: formData.designation,
        department: formData.department,
        employment_type: formData.employment_type || 'Full-Time',
        office_location: formData.office_location,
        board_or_committee_approval_reference: formData.board_or_committee_approval_reference,
        total_options_granted: formData.total_options_granted,
        option_type: formData.option_type || 'Equity Stock Option',
        exercise_price: formData.exercise_price,
        currency: formData.currency || 'INR',
        fair_market_value: formData.fair_market_value || '',
        vesting_start_date: formData.vesting_start_date,
        cliff_period: formData.cliff_period,
        vesting_frequency: formData.vesting_frequency,
        vesting_schedule: formData.vesting_schedule,
        performance_conditions: formData.performance_conditions || '',
        accelerated_vesting: formData.accelerated_vesting || '',
        exercise_window: formData.exercise_window,
        exercise_method: formData.exercise_method,
        payment_method: formData.payment_method,
        lapse_rules: formData.lapse_rules,
        transfer_restrictions: formData.transfer_restrictions,
        taxation_clause: formData.taxation_clause,
        confidentiality_required: !!formData.confidentiality_required,
        listed_company: !!formData.listed_company,
        dpiit_startup: !!formData.dpiit_startup,
        foreign_employee: !!formData.foreign_employee,
        cashless_exercise: !!formData.cashless_exercise,
        rsu_grant: !!formData.rsu_grant,
        authorized_signatory: formData.authorized_signatory,
        employee_acceptance_required: !!formData.employee_acceptance_required,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
