export const generateShareTransferPrompt = (formData: any): string => {
    const data = {
        company_name: formData.company_name,
        company_type: formData.company_type || 'Private Limited',
        cin: formData.cin,
        registered_office: formData.registered_office,
        agreement_date: formData.agreement_date,
        transferor_name: formData.transferor_name,
        transferor_address: formData.transferor_address,
        transferee_name: formData.transferee_name,
        transferee_address: formData.transferee_address,
        company_party: !!formData.company_party,
        share_class: formData.share_class,
        share_certificate_numbers: formData.share_certificate_numbers,
        distinctive_numbers: formData.distinctive_numbers,
        number_of_shares: formData.number_of_shares,
        face_value: formData.face_value,
        paid_up_status: formData.paid_up_status,
        purchase_consideration: formData.purchase_consideration,
        currency: formData.currency || 'INR',
        payment_method: formData.payment_method,
        payment_schedule: formData.payment_schedule,
        taxes: formData.taxes,
        stamp_duty_responsibility: formData.stamp_duty_responsibility,
        conditions_precedent: formData.conditions_precedent,
        closing_date: formData.closing_date,
        closing_deliverables: formData.closing_deliverables,
        representations_transferor: formData.representations_transferor,
        representations_transferee: formData.representations_transferee,
        representations_company: formData.representations_company || '',
        pre_closing_covenants: formData.pre_closing_covenants,
        post_closing_covenants: formData.post_closing_covenants,
        indemnity_required: !!formData.indemnity_required,
        confidentiality_required: !!formData.confidentiality_required,
        termination_conditions: formData.termination_conditions,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        startup: !!formData.startup,
        private_company: !!formData.private_company,
        listed_company: !!formData.listed_company,
        foreign_investor: !!formData.foreign_investor,
        employee_shares: !!formData.employee_shares,
        promoter_shares: !!formData.promoter_shares,
        drag_tag_rights: formData.drag_tag_rights || '',
        aoa_restrictions: formData.aoa_restrictions || '',
        shareholders_agreement_reference: formData.shareholders_agreement_reference || '',
        authorized_signatories: formData.authorized_signatories,
        witness_details: formData.witness_details,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
