export const generateIPAssignmentPrompt = (formData: any): string => {
    const data = {
        agreement_number: formData.agreement_number || '',
        effective_date: formData.effective_date,
        commercial_purpose: formData.commercial_purpose,
        assignor: formData.assignor,
        assignee: formData.assignee,
        authorized_representatives: formData.authorized_representatives,
        assigned_ip_assets: formData.assigned_ip_assets,
        ip_categories: formData.ip_categories,
        intellectual_property_definition: formData.intellectual_property_definition,
        assigned_rights: formData.assigned_rights,
        retained_rights: formData.retained_rights || '',
        assignment_type: formData.assignment_type || 'Exclusive',
        territory: formData.territory,
        assignment_duration: formData.assignment_duration,
        effective_assignment_date: formData.effective_assignment_date,
        commercialization_rights: formData.commercialization_rights,
        registration_rights: formData.registration_rights,
        enforcement_rights: formData.enforcement_rights,
        consideration: formData.consideration,
        moral_rights_clause: formData.moral_rights_clause || '',
        representations_and_warranties: formData.representations_and_warranties,
        further_assurances: formData.further_assurances || '',
        confidentiality_clause: formData.confidentiality_clause || '',
        indemnity_clause: formData.indemnity_clause || '',
        limitation_of_liability: formData.limitation_of_liability || '',
        termination_clause: formData.termination_clause || '',
        notice_details: formData.notice_details,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        arbitration_details: formData.arbitration_details || '',
        jurisdiction: formData.jurisdiction,
        miscellaneous_clauses: formData.miscellaneous_clauses,
        software_ip: !!formData.software_ip,
        employee_assignment: !!formData.employee_assignment,
        founder_assignment: !!formData.founder_assignment,
        startup_investment: !!formData.startup_investment,
        patent_assignment: !!formData.patent_assignment,
        trademark_assignment: !!formData.trademark_assignment,
        research_ip: !!formData.research_ip,
        cross_border_transaction: !!formData.cross_border_transaction,
        witnesses: formData.witnesses || '',
        authorized_signatories: formData.authorized_signatories,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        annexures: formData.annexures || ''
    };

    return JSON.stringify(data, null, 2);
};
