export const generatePatentAssignmentPrompt = (formData: any): string => {
    const data = {
        agreement_number: formData.agreement_number || '',
        effective_date: formData.effective_date,
        commercial_purpose: formData.commercial_purpose,
        assignor: formData.assignor,
        assignee: formData.assignee,
        authorized_representatives: formData.authorized_representatives,
        patent_title: formData.patent_title,
        patent_numbers: formData.patent_numbers,
        patent_application_numbers: formData.patent_application_numbers,
        inventor_details: formData.inventor_details,
        filing_dates: formData.filing_dates,
        priority_dates: formData.priority_dates || '',
        grant_dates: formData.grant_dates || '',
        jurisdictions: formData.jurisdictions,
        technology_field: formData.technology_field,
        assigned_patent_rights: formData.assigned_patent_rights,
        patent_family_details: formData.patent_family_details || '',
        associated_know_how: formData.associated_know_how || '',
        technical_documentation: formData.technical_documentation || '',
        assignment_scope: formData.assignment_scope,
        commercialization_rights: formData.commercialization_rights,
        enforcement_rights: formData.enforcement_rights,
        registration_rights: formData.registration_rights,
        territory: formData.territory,
        effective_assignment_date: formData.effective_assignment_date,
        consideration: formData.consideration,
        representations_and_warranties: formData.representations_and_warranties,
        further_assurances: formData.further_assurances,
        confidentiality_clause: formData.confidentiality_clause || '',
        indemnity_clause: formData.indemnity_clause || '',
        limitation_of_liability: formData.limitation_of_liability || '',
        termination_clause: formData.termination_clause || '',
        post_termination_provisions: formData.post_termination_provisions || '',
        notice_details: formData.notice_details,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        arbitration_details: formData.arbitration_details || '',
        jurisdiction: formData.jurisdiction,
        miscellaneous_clauses: formData.miscellaneous_clauses,
        employee_invention: !!formData.employee_invention,
        university_research: !!formData.university_research,
        startup_investment: !!formData.startup_investment,
        patent_family: !!formData.patent_family,
        technology_transfer: !!formData.technology_transfer,
        joint_ownership: !!formData.joint_ownership,
        cross_border_assignment: !!formData.cross_border_assignment,
        witnesses: formData.witnesses || '',
        authorized_signatories: formData.authorized_signatories,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        annexures: formData.annexures || ''
    };

    return JSON.stringify(data, null, 2);
};
