export const generateSoftwareDevPrompt = (formData: any): string => {
    const data = {
        agreement_number: formData.agreement_number || '',
        effective_date: formData.effective_date,
        project_name: formData.project_name,
        commercial_purpose: formData.commercial_purpose,
        client: formData.client,
        developer: formData.developer,
        authorized_representatives: formData.authorized_representatives,
        software_type: formData.software_type,
        platform: formData.platform,
        project_objectives: formData.project_objectives,
        scope_of_services: formData.scope_of_services,
        deliverables: formData.deliverables,
        technical_specifications: formData.technical_specifications,
        milestones: formData.milestones,
        project_start_date: formData.project_start_date,
        project_completion_date: formData.project_completion_date,
        acceptance_testing: formData.acceptance_testing,
        acceptance_criteria: formData.acceptance_criteria,
        payment_structure: formData.payment_structure,
        gst_applicable: formData.gst_applicable !== undefined ? !!formData.gst_applicable : true,
        invoicing_terms: formData.invoicing_terms,
        change_request_process: formData.change_request_process,
        client_responsibilities: formData.client_responsibilities,
        developer_responsibilities: formData.developer_responsibilities,
        intellectual_property_clause: formData.intellectual_property_clause,
        background_ip: formData.background_ip,
        foreground_ip: formData.foreground_ip,
        open_source_components: formData.open_source_components || '',
        confidentiality_clause: formData.confidentiality_clause,
        data_privacy_clause: formData.data_privacy_clause || '',
        information_security_requirements: formData.information_security_requirements,
        warranty_terms: formData.warranty_terms,
        support_and_maintenance: formData.support_and_maintenance,
        service_level_agreement: formData.service_level_agreement || '',
        limitation_of_liability: formData.limitation_of_liability,
        indemnity_clause: formData.indemnity_clause,
        force_majeure: formData.force_majeure,
        termination_clause: formData.termination_clause,
        post_termination_obligations: formData.post_termination_obligations,
        notice_details: formData.notice_details,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        arbitration_details: formData.arbitration_details || '',
        jurisdiction: formData.jurisdiction,
        miscellaneous_clauses: formData.miscellaneous_clauses,
        saas_project: !!formData.saas_project,
        ai_project: !!formData.ai_project,
        mobile_application: !!formData.mobile_application,
        web_application: !!formData.web_application,
        government_project: !!formData.government_project,
        agile_methodology: !!formData.agile_methodology,
        devops_services: !!formData.devops_services,
        cross_border_project: !!formData.cross_border_project,
        witnesses: formData.witnesses || '',
        authorized_signatories: formData.authorized_signatories,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        annexures: formData.annexures || ''
    };

    return JSON.stringify(data, null, 2);
};
