export const generateTrademarkLicensePrompt = (formData: any): string => {
    const data = {
        agreement_number: formData.agreement_number || '',
        effective_date: formData.effective_date,
        commercial_purpose: formData.commercial_purpose,
        licensor: formData.licensor,
        licensee: formData.licensee,
        authorized_representatives: formData.authorized_representatives,
        trademark_details: formData.trademark_details,
        trademark_registration_numbers: formData.trademark_registration_numbers,
        pending_trademark_applications: formData.pending_trademark_applications || '',
        licensed_goods_services: formData.licensed_goods_services,
        license_type: formData.license_type || 'Non-Exclusive',
        territory: formData.territory,
        license_duration: formData.license_duration,
        permitted_use: formData.permitted_use,
        quality_control_requirements: formData.quality_control_requirements,
        royalty_structure: formData.royalty_structure,
        payment_terms: formData.payment_terms,
        taxes: formData.taxes,
        audit_rights: formData.audit_rights || '',
        restrictions: formData.restrictions,
        representations_and_warranties: formData.representations_and_warranties,
        infringement_clause: formData.infringement_clause,
        confidentiality_clause: formData.confidentiality_clause || '',
        termination_clause: formData.termination_clause,
        post_termination_obligations: formData.post_termination_obligations,
        notice_details: formData.notice_details,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        arbitration_details: formData.arbitration_details || '',
        jurisdiction: formData.jurisdiction,
        miscellaneous_clauses: formData.miscellaneous_clauses,
        franchise_license: !!formData.franchise_license,
        brand_license: !!formData.brand_license,
        software_branding: !!formData.software_branding,
        merchandise_license: !!formData.merchandise_license,
        international_license: !!formData.international_license,
        co_branding: !!formData.co_branding,
        ecommerce_distribution: !!formData.ecommerce_distribution,
        witnesses: formData.witnesses || '',
        authorized_signatories: formData.authorized_signatories,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        annexures: formData.annexures || ''
    };

    return JSON.stringify(data, null, 2);
};
