export const generateHRPolicyPrompt = (formData: any): string => {
    const data = {
        company_name: formData.company_name,
        company_type: formData.company_type || 'Private Limited',
        company_logo: formData.company_logo || '',
        registered_office: formData.registered_office,
        policy_version: formData.policy_version || '1.0',
        effective_date: formData.effective_date,
        approved_by: formData.approved_by,
        policy_owner: formData.policy_owner,
        review_frequency: formData.review_frequency || 'Annually',
        employment_policies: formData.employment_policies,
        attendance_policy: formData.attendance_policy,
        working_hours_policy: formData.working_hours_policy,
        leave_policy: formData.leave_policy,
        holiday_policy: formData.holiday_policy,
        remote_work_policy: formData.remote_work_policy || '',
        hybrid_work_policy: formData.hybrid_work_policy || '',
        compensation_policy: formData.compensation_policy,
        benefits_policy: formData.benefits_policy,
        performance_management_policy: formData.performance_management_policy,
        learning_development_policy: formData.learning_development_policy,
        code_of_conduct: formData.code_of_conduct,
        confidentiality_policy: formData.confidentiality_policy,
        information_security_policy: formData.information_security_policy,
        intellectual_property_policy: formData.intellectual_property_policy,
        posh_policy: formData.posh_policy || '',
        health_safety_policy: formData.health_safety_policy,
        grievance_policy: formData.grievance_policy,
        disciplinary_policy: formData.disciplinary_policy,
        separation_policy: formData.separation_policy,
        statutory_compliance: formData.statutory_compliance,
        amendment_policy: formData.amendment_policy,
        acknowledgment_text: formData.acknowledgment_text,
        company_industry: formData.company_industry || 'Information Technology',
        startup: !!formData.startup,
        remote_first: !!formData.remote_first,
        global_operations: !!formData.global_operations,
        authorized_signatory: formData.authorized_signatory,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_policies: formData.additional_policies || ''
    };

    return JSON.stringify(data, null, 2);
};
