export const generateIndependentContractorPrompt = (formData: any): string => {
    const data = {
        agreement_date: formData.agreement_date,
        client_name: formData.client_name,
        client_type: formData.client_type || 'Company',
        client_address: formData.client_address,
        contractor_name: formData.contractor_name,
        contractor_type: formData.contractor_type || 'Individual',
        contractor_address: formData.contractor_address,
        contractor_registration_details: formData.contractor_registration_details || '',
        engagement_type: formData.engagement_type || 'Technology Services',
        effective_date: formData.effective_date,
        commencement_date: formData.commencement_date,
        expiry_date: formData.expiry_date,
        renewal_terms: formData.renewal_terms || '',
        scope_of_services: formData.scope_of_services,
        deliverables: formData.deliverables,
        milestones: formData.milestones || '',
        acceptance_criteria: formData.acceptance_criteria,
        fee_structure: formData.fee_structure,
        payment_schedule: formData.payment_schedule,
        reimbursement_policy: formData.reimbursement_policy || '',
        gst_applicable: !!formData.gst_applicable,
        gst_registration_number: formData.gst_registration_number || '',
        tax_responsibility: formData.tax_responsibility,
        client_obligations: formData.client_obligations,
        contractor_obligations: formData.contractor_obligations,
        intellectual_property_clause: formData.intellectual_property_clause,
        confidentiality_clause: formData.confidentiality_clause,
        data_processing: formData.data_processing || '',
        non_solicitation: formData.non_solicitation || '',
        non_compete: formData.non_compete || '',
        insurance_requirements: formData.insurance_requirements || '',
        limitation_of_liability: formData.limitation_of_liability,
        indemnity_clause: formData.indemnity_clause,
        termination_conditions: formData.termination_conditions,
        notice_period: formData.notice_period,
        force_majeure: formData.force_majeure,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        electronic_execution: !!formData.electronic_execution,
        authorized_signatories: formData.authorized_signatories,
        witness_details: formData.witness_details || '',
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
