export const generateInternshipAgreementPrompt = (formData: any): string => {
    const data = {
        agreement_date: formData.agreement_date,
        organization_name: formData.organization_name,
        organization_type: formData.organization_type || 'Private Limited',
        organization_address: formData.organization_address,
        intern_name: formData.intern_name,
        intern_address: formData.intern_address,
        educational_institution: formData.educational_institution || '',
        institution_address: formData.institution_address || '',
        internship_title: formData.internship_title,
        department: formData.department,
        reporting_supervisor: formData.reporting_supervisor,
        internship_mode: formData.internship_mode || 'Office',
        commencement_date: formData.commencement_date,
        end_date: formData.end_date,
        duration: formData.duration,
        working_days: formData.working_days,
        working_hours: formData.working_hours,
        learning_objectives: formData.learning_objectives,
        scope_of_work: formData.scope_of_work,
        training_plan: formData.training_plan,
        mentor_details: formData.mentor_details,
        stipend_type: formData.stipend_type || 'Paid',
        stipend_amount: formData.stipend_amount || '',
        reimbursement_policy: formData.reimbursement_policy || '',
        payment_schedule: formData.payment_schedule || '',
        confidentiality_clause: formData.confidentiality_clause,
        intellectual_property_clause: formData.intellectual_property_clause,
        data_processing: formData.data_processing || '',
        attendance_requirements: formData.attendance_requirements,
        organization_obligations: formData.organization_obligations,
        intern_obligations: formData.intern_obligations,
        certificate_of_completion: formData.certificate_of_completion || '',
        ppo_eligibility: formData.ppo_eligibility || '',
        termination_conditions: formData.termination_conditions,
        notice_period: formData.notice_period,
        governing_law: formData.governing_law,
        dispute_resolution: formData.dispute_resolution,
        academic_reporting: formData.academic_reporting || '',
        electronic_execution: !!formData.electronic_execution,
        authorized_signatories: formData.authorized_signatories,
        institution_signatory: formData.institution_signatory || '',
        witness_details: formData.witness_details || '',
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
