export const generateProbationConfirmationPrompt = (formData: any): string => {
    const data = {
        company_name: formData.company_name,
        company_type: formData.company_type || 'Private Limited',
        cin: formData.cin || '',
        registered_office: formData.registered_office,
        letter_number: formData.letter_number || '',
        issue_date: formData.issue_date,
        employee_name: formData.employee_name,
        employee_id: formData.employee_id || '',
        designation: formData.designation,
        department: formData.department,
        joining_date: formData.joining_date,
        probation_start_date: formData.probation_start_date,
        probation_completion_date: formData.probation_completion_date,
        confirmation_effective_date: formData.confirmation_effective_date,
        reporting_manager: formData.reporting_manager,
        work_location: formData.work_location,
        appointment_letter_reference: formData.appointment_letter_reference,
        employment_agreement_reference: formData.employment_agreement_reference || '',
        salary_revision: !!formData.salary_revision,
        revised_compensation: formData.revised_compensation || '',
        revised_compensation_effective_date: formData.revised_compensation_effective_date || '',
        permanent_employee_benefits: formData.permanent_employee_benefits || '',
        confidentiality_required: !!formData.confidentiality_required,
        intellectual_property_required: !!formData.intellectual_property_required,
        transferability: formData.transferability || '',
        esop_eligibility: formData.esop_eligibility || '',
        promotion_details: formData.promotion_details || '',
        senior_management: !!formData.senior_management,
        remote_employee: !!formData.remote_employee,
        hybrid_employee: !!formData.hybrid_employee,
        authorized_signatory: formData.authorized_signatory,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
