export const generateWarningLetterPrompt = (formData: any): string => {
    const data = {
        company_name: formData.company_name,
        company_type: formData.company_type || 'Private Limited',
        cin: formData.cin || '',
        registered_office: formData.registered_office,
        letter_number: formData.letter_number || '',
        issue_date: formData.issue_date,
        employee_name: formData.employee_name,
        employee_id: formData.employee_id,
        designation: formData.designation,
        department: formData.department,
        subject: formData.subject,
        incident_date: formData.incident_date,
        incident_description: formData.incident_description,
        policy_violations: formData.policy_violations,
        investigation_reference: formData.investigation_reference || '',
        show_cause_notice_reference: formData.show_cause_notice_reference || '',
        employee_explanation_summary: formData.employee_explanation_summary || '',
        findings: formData.findings || '',
        warning_type: formData.warning_type || 'First',
        corrective_action_plan: formData.corrective_action_plan,
        monitoring_period: formData.monitoring_period || '',
        consequences_of_repeat_misconduct: formData.consequences_of_repeat_misconduct || '',
        attendance_issue: !!formData.attendance_issue,
        performance_issue: !!formData.performance_issue,
        information_security_issue: !!formData.information_security_issue,
        safety_violation: !!formData.safety_violation,
        posh_related: !!formData.posh_related,
        previous_warning_reference: formData.previous_warning_reference || '',
        hr_representative: formData.hr_representative || '',
        authorized_signatory: formData.authorized_signatory,
        execution_place: formData.execution_place,
        execution_date: formData.execution_date,
        annexures: formData.annexures || '',
        additional_conditions: formData.additional_conditions || ''
    };

    return JSON.stringify(data, null, 2);
};
